# SETUP THE API
require '../examples/setup_api'

# CREATE THE ENDPOINT
endpoint = TransactionalEmails.new


# GET ALL ITEMS
response = endpoint.get_emails(page = 1, per_page = 10)

# DISPLAY RESPONSE
puts response.body


# GET ONE ITEM
response = endpoint.get_email(email_uid = 'EMAIL_UNIQUE_ID')

# DISPLAY RESPONSE
puts response.body


# CREATE A NEW EMAIL
response = endpoint.create(data = {
    'to_name': 'John Doe', # required
    'to_email': 'john@doe.com', # required
    'from_name': 'Jane Doe', # required
    'from_email': 'jane@doe.com', # optional
    'reply_to_name': 'Jane Doe', # optional
    'reply_to_email': 'jane@doe.com', # optional
    'subject': 'This is the email subject', # required
    'body': 'Hello world!', # required
    'plain_text': 'Hello world!', # optional, will be autogenerated if missing
    'send_at': Time.now.strftime('%Y-%m-%d %H:%M:%S'), # required, UTC date time in same format!
})

# DISPLAY RESPONSE
puts response.body


# DELETE EMAIL
response = endpoint.delete('EMAIL_UNIQUE_ID')

# DISPLAY RESPONSE
puts response.body

